server.port=8082
spring.application.name=USER-SERVICE

#Swagger config
springdoc.swagger-ui.path=/user/swagger-ui
springdoc.api-docs.path=/user/api-docs

#hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Explicit Hibernate dialect for MySQL to avoid JDBC metadata lookup issues
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
logging.level.sql=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

#mysql db config - local database
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/filenomoved-db?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root